/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Enzo-PC
 */
public class viewMenu extends javax.swing.JFrame {

    /**
     * Creates new form viewMenu
     */
    public viewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtImgUni = new javax.swing.JLabel();
        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAltaDeAlumnos = new javax.swing.JMenuItem();
        jMenuListaDeAlumnos = new javax.swing.JMenuItem();
        jMenubuscarAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAñadirMateria = new javax.swing.JMenuItem();
        jMenuRegistroMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuInscripciones = new javax.swing.JMenuItem();
        jMenuManipulacionNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuAlumnosPorMateria = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(153, 204, 0));
        escritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        escritorio.setFocusable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo universidad de la punta.png"))); // NOI18N

        txtImgUni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R.jpg"))); // NOI18N

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(txtImgUni, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(1070, 1070, 1070)
                .addComponent(jLabel1))
            .addComponent(txtImgUni, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel1))
            .addComponent(txtImgUni, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBarMenu.setBackground(new java.awt.Color(102, 153, 0));

        jMenu1.setBackground(new java.awt.Color(51, 102, 0));
        jMenu1.setText("Alumnos");

        jMenuAltaDeAlumnos.setText("Alta de Alumnos ");
        jMenuAltaDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAltaDeAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAltaDeAlumnos);

        jMenuListaDeAlumnos.setText("Lista de Alumnos");
        jMenuListaDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListaDeAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuListaDeAlumnos);

        jMenubuscarAlumnos.setText("Buscar Alumnos");
        jMenubuscarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenubuscarAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenubuscarAlumnos);

        jMenuBarMenu.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(51, 102, 0));
        jMenu2.setText("Materias");

        jMenuAñadirMateria.setText("Añadir Materia");
        jMenuAñadirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAñadirMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAñadirMateria);

        jMenuRegistroMateria.setText("Registro Materia");
        jMenuRegistroMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistroMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRegistroMateria);

        jMenuBarMenu.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(51, 102, 0));
        jMenu3.setText("Administracion");

        jMenuInscripciones.setText("Manejo de incripciones");
        jMenuInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuInscripciones);

        jMenuManipulacionNotas.setText("Manipulacion de notas");
        jMenuManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuManipulacionNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuManipulacionNotas);

        jMenuBarMenu.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(51, 102, 0));
        jMenu4.setText("Consultas");

        jMenuAlumnosPorMateria.setText("Alumnos por materia");
        jMenuAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAlumnosPorMateria);

        jMenuBarMenu.add(jMenu4);

        jMenuSalir.setBackground(new java.awt.Color(51, 102, 0));
        jMenuSalir.setText("Salir");

        jItemSalir.setText("Salir");
        jItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jItemSalir);

        jMenuBarMenu.add(jMenuSalir);

        setJMenuBar(jMenuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jMenubuscarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenubuscarAlumnosActionPerformed
        viewBuscarXDni vBuscarAlum = new viewBuscarXDni();
        escritorio.add(vBuscarAlum);
        vBuscarAlum.setVisible(true);
    }//GEN-LAST:event_jMenubuscarAlumnosActionPerformed

    private void jMenuInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInscripcionesActionPerformed
        viewIncripcion vI = new viewIncripcion();
        escritorio.add(vI);
        vI.setVisible(true);
    }//GEN-LAST:event_jMenuInscripcionesActionPerformed

    private void jMenuManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuManipulacionNotasActionPerformed
        viewCargaNotas vCN = new viewCargaNotas();
        escritorio.add(vCN);
        vCN.setVisible(true);
    }//GEN-LAST:event_jMenuManipulacionNotasActionPerformed

    private void jMenuAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnosPorMateriaActionPerformed
        viewListaAlumXMateria vLAXM = new viewListaAlumXMateria();
        escritorio.add(vLAXM);
        vLAXM.setVisible(true);
    }//GEN-LAST:event_jMenuAlumnosPorMateriaActionPerformed

    private void jItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemSalirActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jItemSalirActionPerformed

    private void jMenuAltaDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaDeAlumnosActionPerformed
        viewAltaAlumno altaAlumno = new viewAltaAlumno();
        escritorio.add(altaAlumno);
        altaAlumno.setVisible(true);
    }//GEN-LAST:event_jMenuAltaDeAlumnosActionPerformed

    private void jMenuListaDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListaDeAlumnosActionPerformed
        viewListaAlumno listaAlumno = new viewListaAlumno();
        escritorio.add(listaAlumno);
        listaAlumno.setVisible(true);
    }//GEN-LAST:event_jMenuListaDeAlumnosActionPerformed

    private void jMenuAñadirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAñadirMateriaActionPerformed
        viewMateria vM= new viewMateria();
        escritorio.add(vM);
        vM.setVisible(true);
    }//GEN-LAST:event_jMenuAñadirMateriaActionPerformed

    private void jMenuRegistroMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistroMateriaActionPerformed
        viewRegistroMateria viewRM = new viewRegistroMateria();
        escritorio.add(viewRM);
        viewRM.setVisible(true);
    }//GEN-LAST:event_jMenuRegistroMateriaActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jItemSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAltaDeAlumnos;
    private javax.swing.JMenuItem jMenuAlumnosPorMateria;
    private javax.swing.JMenuItem jMenuAñadirMateria;
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenuItem jMenuInscripciones;
    private javax.swing.JMenuItem jMenuListaDeAlumnos;
    private javax.swing.JMenuItem jMenuManipulacionNotas;
    private javax.swing.JMenuItem jMenuRegistroMateria;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenuItem jMenubuscarAlumnos;
    private javax.swing.JLabel txtImgUni;
    // End of variables declaration//GEN-END:variables
}
